services:
  mock-server:
    build:
      context: .
      dockerfile: mock-server/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${VITE_BACKEND_SERVER_PORT}:${VITE_BACKEND_SERVER_PORT}"
    networks:
      - server_network

networks:
  server_network:
    driver: bridge
