name: Run UTs

on:
  workflow_run:
    workflows: ["Stage Delivery"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y make docker-compose

    - name: Run UTs (Unit Tests)
      run: make run-uts
